library(lab6package)
library(profvis)
source("R/knapsack_functions.R")
profvis(brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500))
profvis(knapsack_dynamic(x = knapsack_objects[1:500,], W = 500))
profvis(greedy_knapsack(x = knapsack_objects[1:500,], W = 500))
source("R/knapsack_functions.R")
profvis(greedy_knapsack(x = knapsack_objects[1:500,], W = 500))
profvis(greedy_knapsack2(x = knapsack_objects[1:500,], W = 500))
profvis(brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500, parallel =TRUE))
